### ISSUE TITLE
Production authentication

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#13]
Integrate with college's AD directory

**Comment by tydingsl** [comment]
@smattingly I'm assuming this issue can be closed?

**Comment by smattingly** [comment]
Not really. The login code I put in is fake-- for development purposes. There is an obstacle here: the real login code talks to a college server to check credentials, and the college server will only talk with our production server. It's firewall blocks traffic from, say, random c9 workspaces. This may have to sit until I can test on the production server.

**Comment by smattingly** [comment]
Fixed [here](https://github.com/dewv/nlcAttendance/commit/f4bddc47f6e12909fa5fc80a01903a1c42db1c53). Code will always do "fake development" authentication unless `sails.config.custom.ldap` is defined-- presumably in `config/local.js`. That file is not stored in git/github because of sensitive contents. A copy of the file for using the college AD server is stored in the usual place for sensitive group files.
