### ISSUE TITLE
Issue Downloading Session Data

### ISSUE THREAD

**Issue by brownk3** [dewv/nlcAttendance#149]
Email from customer:

> Good morning,
>  
> Each Monday, I pull the NLC session usage and sort out the previse week's usage to report to athletics.
>  
> This morning the download feature appears to not be working. Two requests, 1) if you can email me all the download data today so I can sort that would be appreciated, and 2) if you can fix the issue before next week that would be great.
>  
> Best,
> Derek

**Comment by smattingly** [comment]
Adding database indexes did not seem to help the problem. There seem to be three possible reasons (not mutually exclusive) for the slow performance.
1. the free tier MongoDB Atlas service does not give us very good server specs, esp. RAM. This is probably the biggest contributor. Fixing this would require $.
2. we are not used to thinking in terms of multiple network hops. That is, *now* the data travels from the Atlas DB server to our app server and then to the client-- that's an extra "hop" which may be apparent when moving multiple records. Presumably this is not a big issue, because everything is distributed in the clouds these days.
3. there was room for improved efficiency in our app code. I don't really like that we had to do this, because I feel that the DB layer should take care of optimizing performance of data fetching. But, assuming the limited RAM is the cause, and that we won't be fixing that, I found a way to reduce the fetching required: [55db71b](https://github.com/dewv/nlcAttendance/commit/55db71b89422ceed4e7c2f5f2abf3e11d449b428). The download was taking too long with the ~400 visits we had through the first 4 weeks. With the fix, the download did not time out until > 2000 visits; hopefully that will be okay for a semester based on a rate of 100/week.

I will be releasing that fix shortly.
