### ISSUE TITLE
Student Update Form

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#20]
Student update form in views needs to be made

**Comment by brosekerg** [comment]
can i do this one?

**Comment by smattingly** [comment]
@brosekerg I see that you self-assigned this. Only managers may assign tasks-- in this case @tydingsl. Even if the manager has communicated the Issue is yours, the manager makes the assignment in GitHub. Also, the discussion like "Can I have this one?" should happen in the team discussion thread for that purpose, not on the Issue itself. Please respond with an "OK" (or questions) so I know you've seen this.

**Comment by brosekerg** [comment]
OK

**Comment by smattingly** [comment]
@tydingsl @brosekerg This form is in place, and I'm not aware of anything that needs to be done with it. Lauren, if you agree please close it; otherwise please clarify what needs doen.
